version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
        - "8080:8080"
    restart: always
    environment:
      APP_BOOTSTRAP_SERVER: 127.0.0.1
      MOCEAN_API_KEY:
      MOCEAN_API_SECRET:
      MOCEAN_FROM: