version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
        - "8080:8080"
    restart: always
    environment:
      APP_BOOTSTRAP_SERVER: 127.0.0.1
      MOCEAN_API_KEY: 9849ad8e
      MOCEAN_API_SECRET: 2ed9f09d
      MOCEAN_FROM: Lalosaimi